### ISSUE TITLE
Manifest Error

### ISSUE THREAD

**Issue by ghost** [vhoen/Android-Geofence-21#1]
Hi.. First of all thank you very much for such a great article and source shared.
I am trying to implement the code and run it. I got an error (red underline) in the manifest.xml that tell me:-
".Geofencereceiver cannot be assigned to Broadcastreceiver" in the <<receiver> tag.

[The program runs nevertheless]

Can you please consider telling me what is the error means?

Thanks again for your effort, kindness and time.

**Comment by vhoen** [comment]
Hi,

I have no idea what this error means, I never saw it. I  will check it next week when I will be back in front of my computer.

Thanks for your feedback

**Comment by ghost** [comment]
Sure. Thanks.

**Comment by vhoen** [comment]
I cannot reproduce it, could you please send me your manifest.xml (don't forget to remove you api key) ?
